services:
  postgres:
    image: postgres:latest
    container_name: site_doces_database
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=site_doces
    restart: always
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080

volumes:
  postgres:
    name: site_doces_database